### ISSUE TITLE
Add usage statistics

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-connect#235]
Randomized anonymous usage statistics should be collected for Connect in the same way that it's collected for all other Vaadin products. As an example of how this is done, see https://github.com/vaadin/vaadin-router/blob/master/src/router-meta.js.

To reduce the production mode overhead even further than what's possible for frontend-only products, we could hook things up so that the usage statistics logic is produced by the code generator. The code generator would thus only include the usage statistics code when it's run for a development mode build. The generated code would still also use the regular runtime development mode detector, so it's not the end of the world even if there are some edge cases where it would also be generated into production mode code.

**Comment by vlukashov** [comment]
Only generating the usage statistics invoking code in the development mode would require several steps:
 - add a usage statistics recording code snippet into the `connect` npm package
 - add a 'mode' (production / development) configuration option to the JS code generator (and to the connect maven plugin)
 - use the 'mode' option in the JS generator to add / skip adding the usage statistics code into every generated JS wrapper (adding it into the default connect client is not enough because it [can be overridden](https://github.com/vaadin/vaadin-connect/issues/163) with a custom one that would not have the usage statistics in it)
 - update the starter to have two separate maven profiles: development and production and set the connect maven plugin's 'mode' to 'development' in the development profile

Always generating the usage statistics invoking code (and relying on the run-time dev mode detector) would require less steps:
 - add a usage statistics recording code snippet into the `connect` npm package
 - update the JS generator so that it adds the usage statistics code into every generated JS wrapper (adding it into the default connect client is not enough because it [can be overridden](https://github.com/vaadin/vaadin-connect/issues/163) with a custom one that would not have the usage statistics in it)

**Comment by Legioth** [comment]
I don't see why it would be necessary to involve the JS generator for the case when only runtime detection is used. Why can't it be hardcoded into the init of any module that would be imported from the `connect` npm package?

**Comment by vlukashov** [comment]
> I don't see why it would be necessary to involve the JS generator for the case when only runtime detection is used. Why can't it be hardcoded into the init of any module that would be imported from the `connect` npm package?

Good point. Indeed, in this case it's fine if the usage statistics snippet in the `connect` package is always called when the `@vaadin/connect` module is imported. I've updated my comment above.
