### ISSUE TITLE
avoid re-login on backend restart

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#238]
When making changes to the backend Java code I want the JWT secret key to remain the same, so that I do not have to re-login after every backend change.

DoD:
- there is a new goal specified in the Maven plugin, which runs automatically on the appropriate phase, when the application resources could be modified
- it looks at the application.properties file
  - if the signing key configuration property is missing or is an empty string, which probably happens on the first run, it generates a new random singing key, writes the new key to the application properties file, and outputs a log line saying that the signing key was missing and generated automatically for the user
  - otherwise, no action, no need to change an existing signing key
- there is a test for this feature
- any docs that refer to the 'random signing key' feature are updated

**Comment by Legioth** [comment]
Why not stick to the original idea that the properties file is automatically updated to contain a randomized key? I know it's a little bit nasty for the application to rewrite its own configuration file, but this is something that would only happen the first time the application is launched.

I still see that as preferable over the risk that there might be applications running with a predictable key only because the developer is lazy and ignores the *HUGE* warnings in their server logs.

**Comment by platosha** [comment]
**UPD: DoD changed to automatically generate the key on the first run**
