### ISSUE TITLE
TS generator does not generate useful types for Java `Optional<T>`

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#340]
When generating TypeScript wrappers with vaadin-connect-maven-plugin I expect to see a specific TS type (not `any`) to be used in a service method signature where the Java type is `Optional<Bean>`. Currently, this is not the case:

Java service class
```java
@VaadinService
public class ContactEndpoint {

    public Optional<Contact> get(Long id) {
        return repository.findById(id);
    }
```

Generated TS service module:
```typescript
export function get(
  id: number
): Promise<any> {
}
```

This does not give any type information in TS code. Expected to see something like `function get(id: number): Promise<Contact | null>`.

**Comment by vlukashov** [comment]
Included use cases:
 - return type (e.g. `public Optional<Contact> get(Long id)`)
 - parameter type (e.g. `public Long getId(Optional<Contact> contact)`)
 - field type (e.g. `private Optional<Contact> contact;`)

Excluded use cases:
 - part of a complex type (e.g. `Map<Optional<Contract>, String>`)

**Comment by SomeoneToIgnore** [comment]
The PR https://github.com/vaadin/vaadin-connect/pull/356 (branch https://github.com/vaadin/vaadin-connect/tree/kb/340_optional-type-generated) was closed due to discussion in https://vaadin.slack.com/archives/CDNTYMS9H/p1551986388008400

If we agree with the proposition from Slack, we will be forced to make every type as optional which will 
make the PR almost obsolete.

Needs further discussion.
