### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by soberich** [vaadin/vaadin-connect#440]
Is this abandoned?
I think this is the best approach, when it came out in "labs" (https://vaadin.com/labs/vaadin-connect) I was thinking "that's it - finally they did it!", but I see it's not moving...

**Comment by Haprog** [comment]
The `vaadin-connect` experiment has been integrated into Vaadin [Flow](https://github.com/vaadin/flow) since Flow 3.0.0 (which is part of Vaadin 15) and its features are being developed and maintained as part of the `flow` repository.

I notice it can seem confusing if you nowadays find this `vaadin-connect` repository or the old Labs page for it. This repository readme or description should probably be updated to mention the above and this repository archived.

If you want to use the latest version of these features, you probably want to try out Vaadin 16 or Vaadin 17 beta. See the documentation at https://vaadin.com/docs/v17/flow/typescript/quick-start-guide.html and https://vaadin.com/docs/v17/flow/client-side-forms/tutorial-binder.html

At https://start.vaadin.com/ you can choose to create a new project with Vaadin 16 or 17 and TypeScript based views.

We're also working on a new tutorial for creating an application with Vaadin and TypeScript views, if you want to take a sneak peek at the tutorial project code here https://github.com/vaadin-learning-center/crm-tutorial-typescript/ (work in progress).

**Comment by soberich** [comment]
Indeed this is confusing.
Thank you.
