### ISSUE TITLE
remove the client secret from the Vaadin Connect auth server

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#58]
The default Vaadin Connect auth server should not require a client id / client secret to access the token endpoint because Vaadin Connect clients are expected to be public (not capable of keeping a secret) and therefore using a client secret is pointless.

DoD:
 - both the client id and the client secret are removed from the project code, tests, demos and docs, including:
    - the default auth server backend is updated in the way described below so that so that  the `/oauth/token` endpoint does not require a client id / secret
    - the JS auth client is updated to not send a id / secret
    - the client id and secret are removed from the Vaadin Connect properties
 - there is a custom servlet filter for the token endpoint that injects a synthetic `Principal` into the security context as if the request had a correct Basic HTTP auth header for a (hard-coded) `vaadin-connect-client` user. That way Spring Security OAuth2 Authorization Server implementation works without any changes, and the clients do not need to worry about a client id (effectively, all HTTP requests to the token endpoint would automatically be authenticated). See the Manolo's comment below for details.

**Comment by Legioth** [comment]
The same also goes for the client id, since it's only used in association with the client secret when using the Password grant flow.

**Comment by vlukashov** [comment]
time box 1 day to investigate the possibilities with spring-security-oauth2

**Comment by vlukashov** [comment]
Check the updated OAuth2 support in Spring 5: https://docs.spring.io/spring-security/site/docs/5.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#oauth2resourceserver

**Comment by manolo** [comment]
Spring Oauth2 is developed under the assumption that token endpoints are authenticated.

We probably might bypass `/oauth/token` authentication defined in [AuthorizationServerSecurityConfiguration](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/AuthorizationServerSecurityConfiguration.java#L89)
by providing our own WebSecurityConfigurerAdapter, but it does not fix the issue since there is a second check in [TokenEndpoint](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/TokenEndpoint.java#L90)
requiring a `principal` Authentication object. I've not found an easy way to replace the TokenEndpoint implementation though.

Spring security automatically adds the BasicAuthenticationFilter that allows to generate a principal to be checked in TokenEndpoint when appropriate http headers are set, but the only configurable parameter in spring-oauth2 is to change the way this authentication is done (using forms insteaad of basic http auth) by setting the `allowFormAuthenticationForClients` flag in the `AuthorizationServerSecurityConfigurer` but still we need an authenticated request.

The easiest way I found to avoid client sending http basic-auth headers, is to use the API in the oauth2 implementation of adding a filter before BasicAuthenticationFilter happens, it allows us to stub the request and automatically add the client information to make the request succeed.  This idea is prototyped  in this [branch](https://github.com/vaadin/vaadin-connect/compare/mcm/disable-basic-http-auth?expand=1).
