### ISSUE TITLE
support differential serving in the default Vaadin Connect web server

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#60]
When using the default Vaadin Connect web server I want to send a transpiled ES5 frontend bundle to the browsers that do not support more modern ES features, and a non-transpiled ES6 frontend bundle to the rest, so that I can support a wide range of browsers while still using modern browser features and serve polyfills only to the browsers that require them.

DoD:
 * tbd

**Comment by Legioth** [comment]
To be determined whether the selection is based on a small inlined feature sniffing script or if the decision is made on the server based on the user agent.

Feature sniffing is less fragile since it can also work with unexpected or spoofed user agent strings, but a server-side decision is slightly more performant since the total download size is smaller and the browser can start downloading the bundle slightly earlier.

**Comment by vlukashov** [comment]
Closing this ticket due to the decision to use the `module` / `nomodule` approach to differential serving. See https://github.com/vaadin/vaadin-connect/issues/170#issuecomment-450114923 for details.
